{% set name = "google-api-python-client" %}
{% set version = "2.185.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_api_python_client-{{ version }}.tar.gz
  sha256: aa1b338e4bb0f141c2df26743f6b46b11f38705aacd775b61971cbc51da089c3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - httplib2 >=0.19.0,<1.0.0
    - google-auth >=1.32.0,<3.0.0,!=2.24.0,!=2.25.0
    - google-auth-httplib2 >=0.2.0,<1.0.0
    - google-api-core >=1.31.5,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - uritemplate >=3.0.1,<5

test:
  imports:
    - apiclient
    - googleapiclient
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/google/google-api-python-client/
  license: Apache-2.0 and MIT
  license_file: LICENSE
  summary: Google API Client Library for Python
  dev_url: https://github.com/google/google-api-python-client/
  doc_url: https://developers.google.com/api-client-library/python/start/get_started

extra:
  recipe-maintainers:
    - xylar
    - akrherz
    - ocefpaf
