{% set name = "google-api-python-client" %}
{% set version = "1.7.4" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "05583a386e323f428552419253765314a4b29828c3cee15be735f9ebfa5aebf2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  build:
    - python
    - pip
  run:
    - python
    - google-auth >=1.4.1
    - google-auth-httplib2 >=0.0.3
    - httplib2 >=0.9.2,<1dev
    - oauth2client >=1.5.0,<5.0.0dev
    - six >=1.6.1,<2dev
    - uritemplate >=3.0.0,<4dev

test:
  imports:
    - apiclient
    - googleapiclient
    - googleapiclient.discovery_cache

about:
  home: https://github.com/google/google-api-python-client/
  license: Apache 2.0 and MIT
  summary: 'Google API Client Library for Python'
  dev_url: https://github.com/google/google-api-python-client/
  doc_url: https://developers.google.com/api-client-library/python/start/get_started

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
